# define nre new
# define mian main
# define falg flag
# define ture true
# define flase false
# define inr int
# define iny int
# define sancf scanf
# define print printf
# define printd printf
# define sturct struct
# define soze size
# define retrun return
# define true 1
# define false 0
# define ； ;
# define （ (
# define ） ) 
//这个应该不需要作过多解释了吧 
